config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  patch 'images/:id' => 'images#update'
  get 'images/:id/edit' => 'images#edit', as:'edit_image'

  resources :images do
    resources :likes, only: [:create, :destroy]
  end

  resources :lists do
    resources :likes, only: [:create, :destroy]
  end
  

  post "posts/check_cache_image"
  root 'lists#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user 
    has_many :likes, dependent: :destroy
    has_many :image_tag_relations, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :tags, through: :image_tag_relations, dependent: :destroy
end

app/models/image_tag_relation.rb
class ImageTagRelation < ApplicationRecord
  belongs_to :image
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :image
  belongs_to :user

  validates_uniqueness_of :image_id, scope: :user_id
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
    has_many :image_tag_relations, dependent: :destroy
    has_many :images, through: :image_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :images, dependent: :destroy
         validates :name, presence: true 
         validates :profile, length: { maximum: 200 } 
         has_many :likes, dependent: :destroy
         has_many :liked_images, through: :likes, source: :image
         mount_uploader :image, ImageUploader

         def already_liked?(image)
          self.likes.exists?(image_id: image.id)
        end  
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
    end
end 

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    
    def index

      @images = Image.all
     
      if params[:search] == nil && params[:search] != ''
        search = params[:search]
        @images = Image.joins(:user).where("color LIKE ? OR place LIKE ?", "%#{search}%", "%#{search}%")
      else
        @images = Image.all
      end

      @tags = Tag.all
        search = params[:search]

      @images = Image.joins(:user).where("color LIKE ? OR place LIKE ?", "%#{search}%", "%#{search}%")
        if params[:tag_ids].present?
          image_ids = []
          params[:tag_ids].each do |key, value| 
          if value == "1"
            Tag.find_by(name: key).images.each do |p| 
            image_ids << p.id
          end
        end
      end

        image_ids = image_ids.uniq
          @images = @images.where(id: image_ids) if image_ids.present?
          end
          if params[:tag]
          Tag.create(name: params[:tag])
          end
    end

    

    def new
        @images = Image.new
      end
    
    def create
        images = Image.new(image_params)

        images.user_id = current_user.id

        if images.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end
    
    def show
        @image = Image.find(params[:id])
    end

    def edit
        @image = Image.find(params[:id])
    end

    def update
        image = Image.find(params[:id])
        if image.update(image_params)
          redirect_to :action => "show", :id => image.id
        else
          redirect_to :action => "new"
        end
    end

    private
      def image_params
        params.require(:image).permit(:image, :caption, :category, :color, :place, :Date_taken, tag_ids: [] )
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
      like = current_user.likes.create(image_id: params[:image_id]) 
      redirect_back(fallback_location: root_path)
    end
  
    def destroy
      like = Like.find_by(image_id: params[:image_id], image_id: current_user.id)
      like.destroy
      redirect_back(fallback_location: root_path)
    end
  
  end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
end

app/controllers/sindans_controller.rb
class SindansController < ApplicationController
    def index 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sindans_helper.rb
module SindansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/_form.html.slim
= form_with model: post, local: true do |f|
  
.form-group
  = f.label :image, "画像"
  = f.file_field :image, class:"form-control", id: 'post_img'
.image-preview
  img[id="image_img_prev" src="#" class='hidden']
  - if post.persisted? && post.image?
     = image_tag post.image.url, class: 'image_present_img'
    label
      = f.check_box :remove_image

    - else
      = f.hidden_field :avatar_cache
    span[id="image_isnot_sky" class="hidden"]

    = f.label "タグ"
    ul[id="post-tags"]
    = hidden_field_tag :tag_hidden, tag_list

app/views/images/edit.html.erb
<%= form_for @image do |f| %>
  <div class="field">
  <%= f.label :image %>
  <%= f.file_field :image %>
  </div>
  
  <div class="field">
  <%= f.label :caption %>
  <%= f.text_area :caption, :size => "30x2" %>
  </div>
  
  <div class="field">
  <%= f.label :color  %>
  <%= f.text_field :color, :size => 30 %>
  </div>
  
  <div class="field">
  <%= f.label :place %>
  <%= f.text_field :place, :size => 30 %>
  </div>
  
  <div class="form-group">
  <%= f.label :Date_taken, class: 'control-label' %>
  <%= f.date_select :Date_taken, class: 'form-control' %>
  
  <div class='form-group'>
     <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
          <div class='form-check'>
               <%= tag.label class: 'form-check-label' do %>
                   <%= tag.check_box class: 'form-check-input' %>
                   <%= tag.text %>
               <% end %>
          </div>
      <% end %>
  </div>
    
    <%= f.submit "編集する" %>
    
    <% end %>

app/views/images/index.html.erb
<!DOCTYPE html> 
<html lang="ja">

<head>
    <meta charset="utf-8">
    <title>Imaginativestroll</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="images.scss">
</head>

<body>


  <div class="search">
   <aside class="colorsearch">
     <ul>
     <%= form_tag({controller:"images",action:"index"}, method: :get) do %>
     <%= text_field_tag :search %>
     <%= submit_tag '色・場所で探す', class: "button"  %>
     <% end %>
     </ul>
   </aside>

   <aside class="tagsearch">
     <ul>
     <%= form_tag({controller:"images",action:"index"}, method: :get) do %>
     <% Tag.all.each do |t| %>
     <%= check_box :tag_ids, t.name %><%= t.name %>
     <% end %>
     <%= submit_tag 'カテゴリーで検索', class: "button" %>
     <% end %>
     </ul>
   </aside>
  </div>
 
<dic class="btn02">
<a href="/images/new">新規投稿</a>
</div>

<% if user_signed_in? %>
<a href="/users/<%= current_user.id %>">マイページへ</a>
<% end %>

 <h3>投稿一覧</h3>
 <div class="boxlistgrandparents">
 <div class="boxlistparents">
  <div class="boxlist">
  <% @images.each do |t| %>
   <div class="box">
      <h4>投稿者</h4><p><%= t.user.name %>
      <div class="image">
         <%= image_tag t.image_url, size: "280x210" if t.image? %>
         
      </div>
      
         <% if user_signed_in? %>
         <% if current_user.already_liked?(t) %>
         <%= link_to image_like_path(id: t.id, image_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
         <% else %>
         <%= link_to image_likes_path(id: t.id, image_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
         <% end %>
         <% else %>
           <i class="far fa-heart"></i><%= t.likes.count %>
         <% end %>
      
         <h4>caption</h4><%= t.caption %>
         <h4>color</h4><%= t.color %>
         <h4>place</h4><%= t.place %>
         <h4>category</h4><% t.tags.each do |tag| %>
            <span><%= tag.name %></span>
            <% end %>
         <h4>user_name</h4><%= t.user.email %>

         <div class="date"><%= t.Date_taken %></div>

         <p><%= link_to "詳細へ", image_path(t.id) %> 
      
         <% if user_signed_in? && current_user.id == t.user_id %>
           <%= link_to "編集する", edit_image_path(t.id) %>
         <% end %> 
      
   </div>
  <% end %>
 </div>
 </div>
 </div>
<body>

<%= link_to "トップに戻る", lists_path %>

<html>

app/views/images/new.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Imaginativestroll</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="application.css">
    <link rel="stylesheet" type="text/css" href="newimage.css">
</head>

<h3>新規投稿ページ</h3>
<div class="new">

<%= form_for @images do |f| %>

  <div class="field">
  <%= f.label :image %><br/>
  <%= f.file_field :image, class: "image" %>
  </div>
  <div id="image-list"></div>

<div class="field">
<%= f.label :caption %>
<%= f.text_area :caption, :size => "30x2" %>
</div>

<div class="field">
<%= f.label :color_画像に映っている色を書こう  %>
<%= f.text_field :color, :size => 30 %>
</div>

<div class="field">
<%= f.label :place %>
<p><%= f.text_field :place, :size => 30 %></p>
</div>

<div class="form-group">
<%= f.label :Date_taken, class: 'control-label' %>
<p><%= f.date_select :Date_taken, class: 'form-control' %></p>
</div>

<div class='form-group'>
   <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
        <div class='form-check'>
             <%= tag.label class: 'form-check-label' do %>
                 <%= tag.check_box class: 'form-check-input' %>
                 <%= tag.text %>
             <% end %>
            </div>
        <% end %>
</div>

  <%= f.submit "記録する", class: "button" %>
<% end %>
</div>


<%= link_to "一覧に戻る", images_path, class: "button" %>

</html>

app/views/images/show.html.erb
<!DOCTYPE html> 
<html lang="ja">

<head>
    <meta charset="utf-8">
    <title>Imaginativestroll</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="imageshow.css">
</head>


<h3>詳細</h3>
<div class="boxlistgrandparents">
 <div class="boxlistparents">
<div class="boxlist2">

<div class="image">
<div class="box2">
  <h4>投稿者</h4><p><%= @image.user.name %>
  <p><%= image_tag @image.image_url, size: "250x200" if @image.image? %>
  <h4>caption</h4><p><%= @image.caption %>
  <h4>color</h4><p><%= @image.color %>
  <h4>place</h4><p><%= @image.place %>
  <h4>category</h4><p><% @image.tags.each do |tag| %>
    <span><%= tag.name %></span>
    <% end %>
    <div class="date"><%= @image.Date_taken %></div>
  <h4>category</h4><p><%= @image.user.email %>
  <p><%= link_to "編集する", edit_image_path(@image.id) %>
<%= link_to "一覧に戻る", images_path %>

</div>
</div>
</div>
</div>
</div>

<input id="copyTarget" type="text" value="http://localhost:3000/images/1" readonly>
<button onclick="copyToClipboard()">Copy text</button>
        
<script>
        function copyToClipboard() {
            // コピー対象をJavaScript上で変数として定義する
            var copyTarget = document.getElementById("copyTarget");

            // コピー対象のテキストを選択する
            copyTarget.select();

            // 選択しているテキストをクリップボードにコピーする
            document.execCommand("Copy");

            // コピーをお知らせする
            alert("コピーできました！ : " + copyTarget.value);
         }
</script>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Imaginativestroll</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="application.css">
</head>

<body>
<header class="header-content">
    <div class="header-title">🚶Imaginativestroll🚶</div>
  <u1 class="header-list">
  <nav>
   <div class="images-container">
   　 <%= link_to "投稿一覧", images_path, class: "nav-link" %>
      <%= link_to "📸記録する📸", new_image_path, class: "nav-link"  %>
      <% if user_signed_in? %>
      <%= link_to "マイページ", user_path(current_user.id), class: "nav-link" %>
      <% end %>
      <% if user_signed_in? %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link" %>
      <% else %>
      <%= link_to "新規登録", new_user_registration_path, class: "nav-link"  %>
      <%= link_to "ログイン", new_user_session_path, class: "nav-link"  %>
    <% end %>
   </div>
  </nav>
  </u1>
</header>

    <main>
    <%= yield %>
    </main>

    <body>
    　　<title>Imaginativestroll</title>
    　　<meta name="viewport" content="width=device-width,initial-scale=1">
    　　<%= csrf_meta_tags %>
    　　<%= csp_meta_tag %>
    　　<script src=https://kit.fontawesome.com/e40d367649.js></script>
    　　<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    　　<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  　</body>
</body>

<footer>
    <small>©Hinata2023</small>
</footer>

</html>

app/views/lists/index.html.erb
<!DOCTYPE html> 
<html lang="ja">

<head>
    <meta charset="utf-8">
    <title>Imaginativestroll</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="list.scss">
</head>


<body>
<div class= "top">

 <div class= "slide" id="makeImg"> 
 <%= image_tag 'flower.jpg', :size => '69x37' %>
 <%= image_tag 'pool.jpg', :size => '69x37'  %>
 <%= image_tag 'build.jpg', :size => '69x37'  %>
 <%= image_tag 'baloon.jpg', :size => '69x37'  %>
 <%= image_tag 'bird.jpg', :size => '69x37'  %>
 </div>

 <div class= "main">
    <p class="tag"><%= link_to "散歩からアイディアを得よう", images_path, class: "nav-links" %>
    <%= form_tag({controller:"images",action:"index"}, method: :get) do %>
    </p>

    <p class="colorsearch"><%= text_field_tag :search %>
    <%= submit_tag '色・場所で探す', class: "button" %>
    <% end %>
    </p>
 </div>

  <div class= "tagsearch1">
    <p class="tagsearch"><%= form_tag({controller:"images",action:"index"}, method: :get) do %>
    <% Tag.all.each do |t| %>
    <%= check_box :tag_ids, t.name %><%= t.name %>
    <% end %>
    <%= submit_tag 'カテゴリーで検索', class: "button"  %>
    <% end %>
    </p>
   </div>
</div>
</body>

</html>

app/views/sindans/index.html.erb
<header id="commonHeader">
<section id="flowsHead" class="wf-mplus1p">あなたにあった〇〇が1分でわかる</section>
<section id="flows" class="wf-mplus1p">〇〇診断</section>
</header>

<div id="wrapper">
   <div class="sense">
        <article id="pageBody">

            <div class="point_box">
            <div class="box">
            <div class="txt">
            <p>1分だけ下記の質問に答えてみてください。あなたにぴったりの〇〇がわかります!</p>
            </div>
            </div>
            </div>


            <ul class="qalist wf-mplus1p">

            <li id="1" class="question">
                <a name="#1"></a>
                <div class="qbox"><span  class="q">Q.</span>あなたは〜ですか?</div>
                <div class="qabox">
                    <a href="#2" onclick="show(2)" class="qabtn"><div class="btnBox btnBox_y">YES</div></a>
                    <a href="#3" onclick="show(3)" class="qabtn"><div class="btnBox btnBox_n">NO</div></a>
                </div>
            </li>
            <li id="2" class="question" style="display:none;">
                <a name="#"></a>
                <div class="qbox"><span  class="q">Q.</span>〜ですか？</div>
                <div class="qabox">
                    <a href="#101" onclick="show(101)" class="qabtn"><div class="btnBox btnBox_y">YES</div></a>
                    <a href="#102" onclick="show(102)" class="qabtn"><div class="btnBox btnBox_n">NO</div></a>
                </div>
            </li>
            <li id="3" class="question" style="display:none;">
                <a name="#"></a>
                <div class="qbox"><span  class="q">Q.</span>〜ですか？</div>
                <div class="qabox">
                    <a href="#103" onclick="show(103)" class="qabtn"><div class="btnBox btnBox_y">YES</div></a>
                    <a href="#104" onclick="show(104)" class="qabtn"><div class="btnBox btnBox_n">NO</div></a>
                </div>
            </li>
            </ul>

            <div class="answerList">

                <div id="101" style="display:none;" class="answer point_box">
                    <div class="box">
                        <div class="title">
                        <p>あなたに勧める〇〇は<span class="fs-18"><span class="bg-y">『〇〇〇〇』</span></span>です！</p>
                        </div>
                    <div class="txt">
                        <div class="img">
                        <%= image_tag '' %></div>
                        <p>説明会文「タイトル」</p>
<p>詳細を記載</p>
                        <p><a href="#" class="square_btn">もっと詳しくみる</a></p>
                    </div>
                    </div>
                </div>
                <div id="102" style="display:none;" class="answer point_box">
                    <div class="box">
                        <div class="title">
                        <p>あなたに勧める〇〇は<span class="fs-18"><span class="bg-y">『〇〇』</span></span>です！</p>
                        </div>
                    <div class="txt">
                        <div class="img">
                        <%= image_tag '' %></div>
                        <p>説明文「タイトル」</p>
<p>詳細を記載</p>
<p>詳細を記載</p>
<p>詳細を記載</p>
                        <p><a href="#" class="square_btn">もっと詳しくみる</a></p>
                    </div>
                    </div>
                </div>
                <div id="103" style="display:none;" class="answer point_box">
                    <div class="box">
                        <div class="title">
                        <p>あなたに勧める〇〇は<span class="fs-18"><span class="bg-y">『〇〇』</span></span>です！</p>
                        </div>
                    <div class="txt">
                        <div class="img">
                        <%= image_tag '' %></div>
                        <p>説明文「タイトル」</p>
<p>詳細を記載</p>
<p>詳細を記載</p>
<p>詳細を記載</p>
                        <p><a href="#" class="square_btn">もっと詳しくみる</a></p>
                    </div>
                    </div>
                </div>
                <div id="104" style="display:none;" class="answer point_box">
                    <div class="box">
                        <div class="title">
                        <p>あなたに勧める〇〇は<span class="fs-18"><span class="bg-y">説明文「タイトル」</span></span>です！</p>
                        </div>
                    <div class="txt">
                        <div class="img">
                        <%= image_tag '' %></div>
                        <p>説明文「タイトル」</p>
<p>詳細を記載</p>
<p>詳細を記載</p>
<p>詳細を記載</p>
                    </div>
                    </div>
                </div>



        </article>
    </div>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>

<script type="text/javascript">
$(function(){
   $('a[href^=#]').click(function() {
      var speed = 600;
      var href= $(this).attr("href");
      var target = $(href == "#" || href == "" ? 'html' : href);
      var position = target.offset().top;
      $('body,html').animate({scrollTop:position}, speed, 'swing');
      return false;
   });
});
$(function(){
    h = $(window).height();
    h = h-30;
    $(".question").css("min-height", h + "px");
    $(".answerList .box").css("min-height", h + "px");
    
});
function show(idName){ 
    $("#" + idName).show();
}

</script>


</body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<!DOCTYPE html> 
<html lang="ja">

<head>
    <meta charset="utf-8">
    <title>Imaginativestroll</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="usershow.css">
</head>

<h1>mypage</h1>

<div class="mypage">
   <p>名前 : <%= @user.name %></p>
   <p>ユーザー名 : <%= @user.email %></p>
   <p>プロフィール : <%= @user.profile %></p>
   <%= image_tag @user.image_url, size: "250x200" if @user.image? %>
   <% if current_user.id == @user.id %>
    <%= link_to "編集する", edit_user_registration_path %>
   <% end %>
</div>


<h2>記録</h2>
<div class="boxlist1">
<% @user.images.each do |t| %>
 <div class="box1">
  <h4>投稿者</h4><p><%= t.user.name %>
  <p><%= image_tag t.image_url, size: "280x210" if t.image? %>
  <h4>caption</h4><%= t.caption %>
  <h4>color</h4><p><%= t.color %>
  <h4>place</h4><p><%= t.place %>
  <div class="date"><%= t.Date_taken %></div>
  <h4>user name</h4><p><%= t.user.email %>
  <h4>category</h4><p><% t.tags.each do |tag| %>
    <span><%= tag.name %></span>
  <% end %>
 </div>
<% end %>
</div>

<h2>お気に入り</h2>
<div class="boxlist1">
<% @user.liked_images.each do |t| %>
 <div class="box1">
  <h4>投稿者</h4><p><%= t.user.name %>
  <p><%= image_tag t.image_url, size: "250x200" if t.image? %>
  <h4>caption</h4><p><%= t.caption %>
  <h4>color</h4><p><%= t.color %>
  <h4>place</h4><p><%= t.place %>
  <div class="date"><%= t.Date_taken %></div>
  <h4>user name</h4><p><%= t.user.email %>
  <h4>category</h4><p><% t.tags.each do |tag| %>
    <span><%= tag.name %></span>
  <% end %>
 </div>
<% end %>
</div>

</html>